version: '3.8'

services:
  user-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-user:${APP_VERSION}
    container_name: wisepen-user-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod # 必须使用prod, 否则Nacos拉取的是dev的配置（默认），下同
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-user-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/user:/logs
    networks:
      wisepen-net:
        aliases:
          - user-service

  system-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-system:${APP_VERSION}
    container_name: wisepen-system-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-system-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      wisepen-net:
        aliases:
          - system-service

  docs-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-docs:${APP_VERSION}
    container_name: wisepen-docs-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-docs-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/docs:/logs
    networks:
      wisepen-net:
        aliases:
          - docs-service

  resource-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-resource:${APP_VERSION}
    container_name: wisepen-resource-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-resource-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      wisepen-net:
        aliases:
          - resource-service

  document-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-document:${APP_VERSION}
    container_name: wisepen-document-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-document-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      wisepen-net:
        aliases:
          - document-service

  file-storage-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-file-storage:${APP_VERSION}
    container_name: wisepen-file-storage-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-file-storage-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      wisepen-net:
        aliases:
          - file-storage-service

  fudan-extension-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-fudan-extension:${APP_VERSION}
    container_name: wisepen-fudan-extension-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-fudan-extension-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      wisepen-net:
        aliases:
          - fudan-extension-service

  note-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-note:${APP_VERSION}
    container_name: wisepen-note-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-note-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      wisepen-net:
        aliases:
          - note-service

  ai-asset-service:
    image: ${DOCKER_REGISTRY}/wisepencloud-ai-asset:${APP_VERSION}
    container_name: wisepen-ai-asset-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-ai-asset-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      wisepen-net:
        aliases:
          - ai-asset-service

networks:
  wisepen-net:
    external: true
    name: wisepen-net
